server:
  port: 443
  ssl:
    key-store: classpath:itech-admin-api.iskwen.com.jks
    key-store-password: qq19971102
    key-store-type: JKS
spring:
  application:
    name: springboot-test-exam1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuntechlife?serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=utf8&amp;charset=utf8
    username: root
    password: qq19971102
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/drxuid/*"
        allow:
        deny:
        reset-enable: false
        login-username: admin
        login-password: qq19971102
        enabled: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 80
        max-idle: 50
        max-wait: 200ms
        min-idle: 0
    password: qq19971102
    port: 6379
    ssl: false
    timeout: 2000
    expired: 300
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.boot.yuntechlifeadmin.entity.**

jwt:
  config:
    salt: sqgDVsVmwDvsjSbK9iLhZz4t1b6d4PbK
    ttl: 14400000

crossOrigin:
  host: /**

http:
  port: 8080

views:
  host: https://itech-admin.iskwen.com

tencentCloud:
  secretId: AKIDHansoosIjy2hDcnGZggV9hGKH2nXorpg
  secretKey: pS8d6Sj05yjIjy30udAViufPxIRaXKvJ
  cos:
    region: ap-guangzhou
    #ap-tokyo
    bucketName: yuntechlife-guangzhou-1254088237
    #itech-1254088237
    url: https://yuntechlife-guangzhou-1254088237.cos.accelerate.myqcloud.com
    #.cos.accelerate.myqcloud.com
    avatarPath: avatar/admin/
  captcha:
    appId: 2053907131
    secretKey: 08w3JGONdUNxCd6jyKgSQLA**

yunCourier:
  appId: 1010
  token: 1p8m2d5jgua5gyynpkukyaq69r3hl4fv
  lineConfigId: 1

baiduStatistics:
  enable: true
  username: qq948320523
  password: qq19971102SGH
  token: 22c4dfba39b5fb7071ae39642162415c
  siteId: 14788433
  #iTech-admin: 14878137

javamelody:
  enabled: true
  excluded-datasources: secretSource,topSecretSource
  spring-monitoring-enabled: true
  init-parameters:
    log: true
    authorized-users: admin:pwd
    storage-directory: /tmp/javamelody
    monitoring-path: /admin/performance

performance:
  serviceId:
    client: 1
    admin: 2